"""empty message

Revision ID: 21dc0327953b
Revises: 1b0eada1cb54
Create Date: 2016-01-20 21:28:12.737379

"""

# revision identifiers, used by Alembic.
revision = '21dc0327953b'
down_revision = '1b0eada1cb54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    ### end Alembic commands ###
