"""empty message

Revision ID: 192e968ba885
Revises: d8b3abd2d346
Create Date: 2016-03-16 02:22:15.652773

"""

# revision identifiers, used by Alembic.
revision = '192e968ba885'
down_revision = 'd8b3abd2d346'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('creator_name', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'creator_name')
    ### end Alembic commands ###
