"""empty message

Revision ID: 25436ed3b306
Revises: f92d87d037d3
Create Date: 2016-03-20 17:19:07.100793

"""

# revision identifiers, used by Alembic.
revision = '25436ed3b306'
down_revision = 'f92d87d037d3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'replies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('replies', postgresql.ARRAY(JSON()), autoincrement=False, nullable=True))
    ### end Alembic commands ###
