"""empty message

Revision ID: 2ac25ef90f72
Revises: ba8e04902646
Create Date: 2016-03-23 22:35:22.213453

"""

# revision identifiers, used by Alembic.
revision = '2ac25ef90f72'
down_revision = 'ba8e04902646'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('help_text', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'concepts', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'concepts', type_='unique')
    op.drop_column('concepts', 'help_text')
    ### end Alembic commands ###
