"""empty message

Revision ID: 2cc11947b1d5
Revises: 192e968ba885
Create Date: 2016-03-16 22:46:51.007571

"""

# revision identifiers, used by Alembic.
revision = '2cc11947b1d5'
down_revision = '192e968ba885'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
