"""empty message

Revision ID: 5cfdc2ffad35
Revises: c2360480cd5b
Create Date: 2016-03-20 04:30:23.206801

"""

# revision identifiers, used by Alembic.
revision = '5cfdc2ffad35'
down_revision = 'c2360480cd5b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('depth', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('parentUserDisplayName', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('permID', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('picURL', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('recommendations', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('replies', postgresql.ARRAY(postgresql.JSON()), nullable=True))
    op.add_column('comments', sa.Column('reportAbuseFlag', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('trusted', sa.Integer(), nullable=True))
    op.drop_column('comments', 'lft')
    op.drop_column('comments', 'rgt')
    op.drop_column('comments', 'statusID')
    op.drop_column('comments', 'recommendationCount')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('recommendationCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('statusID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('rgt', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('lft', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'trusted')
    op.drop_column('comments', 'reportAbuseFlag')
    op.drop_column('comments', 'replies')
    op.drop_column('comments', 'recommendations')
    op.drop_column('comments', 'picURL')
    op.drop_column('comments', 'permID')
    op.drop_column('comments', 'parentUserDisplayName')
    op.drop_column('comments', 'depth')
    ### end Alembic commands ###
