"""empty message

Revision ID: 6d7beb3315a4
Revises: f6b5eead97b7
Create Date: 2016-03-20 20:51:58.080794

"""

# revision identifiers, used by Alembic.
revision = '6d7beb3315a4'
down_revision = 'f6b5eead97b7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'comments', ['parentID'], ['commentID'])
    op.drop_column('comments', 'replies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('replies', postgresql.ARRAY(VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    ### end Alembic commands ###
