"""empty message

Revision ID: 826505656e67
Revises: 5cfdc2ffad35
Create Date: 2016-03-20 08:23:15.672051

"""

# revision identifiers, used by Alembic.
revision = '826505656e67'
down_revision = '5cfdc2ffad35'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'media')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('media', postgresql.ARRAY(JSON()), autoincrement=False, nullable=True))
    ### end Alembic commands ###
