"""empty message

Revision ID: b758eb9865f6
Revises: 1cdb6a14c9f6
Create Date: 2016-03-14 01:49:49.589801

"""

# revision identifiers, used by Alembic.
revision = 'b758eb9865f6'
down_revision = '1cdb6a14c9f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
