"""empty message

Revision ID: c2360480cd5b
Revises: 192e968ba885
Create Date: 2016-03-19 22:29:54.316828

"""

# revision identifiers, used by Alembic.
revision = 'c2360480cd5b'
down_revision = '192e968ba885'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('adx_keywords', sa.String(), nullable=True),
    sa.Column('column', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('byline', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('des_facet', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('org_facet', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('per_facet', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('geo_facet', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('media', postgresql.ARRAY(postgresql.JSON()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('commentID', sa.Integer(), nullable=False),
    sa.Column('parentID', sa.Integer(), nullable=True),
    sa.Column('statusID', sa.Integer(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=True),
    sa.Column('rgt', sa.Integer(), nullable=True),
    sa.Column('commentSequence', sa.Integer(), nullable=True),
    sa.Column('commentBody', sa.String(), nullable=True),
    sa.Column('commentTitle', sa.String(), nullable=True),
    sa.Column('createDate', sa.DateTime(), nullable=True),
    sa.Column('updateDate', sa.DateTime(), nullable=True),
    sa.Column('approveDate', sa.DateTime(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('userDisplayName', sa.String(), nullable=True),
    sa.Column('userTitle', sa.String(), nullable=True),
    sa.Column('userURL', sa.String(), nullable=True),
    sa.Column('userLocation', sa.String(), nullable=True),
    sa.Column('editorsSelection', sa.Integer(), nullable=True),
    sa.Column('recommendationCount', sa.Integer(), nullable=True),
    sa.Column('replyCount', sa.Integer(), nullable=True),
    sa.Column('assetID', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('commentType', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assetID'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('commentID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('articles')
    ### end Alembic commands ###
