"""empty message

Revision ID: d8b3abd2d346
Revises: 42f0ca2b47de
Create Date: 2016-03-15 23:18:02.727816

"""

# revision identifiers, used by Alembic.
revision = 'd8b3abd2d346'
down_revision = '42f0ca2b47de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'concepts_name_key', 'concepts', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'concepts_name_key', 'concepts', ['name'])
    ### end Alembic commands ###
