"""empty message

Revision ID: e38c2725964b
Revises: 727cde81fa58
Create Date: 2016-03-20 17:14:27.373157

"""

# revision identifiers, used by Alembic.
revision = 'e38c2725964b'
down_revision = '727cde81fa58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'editorsSelection')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('editorsSelection', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
