"""empty message

Revision ID: f6b5eead97b7
Revises: 25436ed3b306
Create Date: 2016-03-20 17:19:37.833594

"""

# revision identifiers, used by Alembic.
revision = 'f6b5eead97b7'
down_revision = '25436ed3b306'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('replies', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'replies')
    ### end Alembic commands ###
