"""empty message

Revision ID: f92d87d037d3
Revises: e38c2725964b
Create Date: 2016-03-20 17:14:52.402664

"""

# revision identifiers, used by Alembic.
revision = 'f92d87d037d3'
down_revision = 'e38c2725964b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('editorsSelection', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'editorsSelection')
    ### end Alembic commands ###
